alias ls='ls -F --color=auto'
alias svim='sudo -E vim'
alias snvim='sudo -E nvim'
alias dcdu='sudo docker compose down && sudo docker compose up -d'
alias ff='fastfetch'
alias aptup='sudo apt update && sudo apt upgrade -y'

